# Generated by Django 4.2.9 on 2024-02-28 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
