# Generated by Django 4.2.9 on 2024-02-20 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
