# Generated by Django 4.2.9 on 2024-02-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0002_grade_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='exam',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='test_1',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='test_2',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
