# Generated by Django 4.2.9 on 2024-02-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_alter_grade_exam_alter_grade_test_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='average',
        ),
        migrations.AddField(
            model_name='grade',
            name='section_average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='grade',
            name='test_average',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
