# Generated by Django 4.2.9 on 2024-02-20 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_remove_grade_average_grade_section_average_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('student', 'subject', 'section', 'year'), name='unique_student_grade'),
        ),
    ]
