# Generated by Django 4.2.9 on 2024-02-20 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0006_alter_grade_classroom_alter_grade_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='section_average',
            field=models.FloatField(blank=True, default=0, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='grade',
            name='test_average',
            field=models.FloatField(blank=True, default=0, editable=False, null=True),
        ),
    ]
