# Generated by Django 4.2.9 on 2024-02-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0010_alter_classroom_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='homeworks', to='sms.subject'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='classroom',
            field=models.ManyToManyField(blank=True, related_name='homeworks', to='sms.classroom'),
        ),
    ]
