# Generated by Django 4.2.9 on 2024-02-28 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0011_homework_subject_alter_homework_classroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homework',
            name='subject',
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeworks', to='sms.subject'),
        ),
    ]
